### ISSUE TITLE
respawn problem

### ISSUE THREAD

**Issue by jumalley** [JoeSzymkowiczFiveM/js5m-ctf#3]
https://streamable.com/lgn706

**Comment by JoeSzymkowiczFiveM** [comment]
Take a look at autoRespawn in the config.

**Comment by JoeSzymkowiczFiveM** [comment]
Also, its hard to tell eve what you think the "problem" is just from that video. Please describe the issue you have. If not, I will close this issue in a couple days.

**Comment by jumalley** [comment]
Hello after all i deleted some delay on the respawn timing and now its working fine ! Thanks for the fast answer ! Great script !

**Comment by jumalley** [comment]
```
local function GetDeaded()
    if not isDead then
        isDead = true
        if carryingFlag then
            DetachFlag()
        end
        if Config.Rules['autoRespawn'] then
            --Wait(Config.Rules['respawnTime']*1000)
            RespawnAtBase()
        end
    end
end
```

**Comment by jumalley** [comment]
Its probably due to the animation i'm using while respawning the player
